
CREATE TABLE  "APPAREIL" 
   (	"CODETYPE" CHAR(3), 
	"NBPLACE" NUMBER(3,0), 
	"DESIGN" VARCHAR2(50), 
	 PRIMARY KEY ("CODETYPE") ENABLE
   )
/
CREATE TABLE  "AVION" 
   (	"NUAVION" CHAR(4), 
	"TYPE" CHAR(3), 
	"ANNSERV" NUMBER(4,0), 
	"NOM" VARCHAR2(50) DEFAULT '', 
	"NBHVOL" NUMBER(8,0), 
       CONSTRAINT "fk_AV" FOREIGN KEY("TYPE") REFERENCES APPAREIL("CODETYPE") ENABLE,
	 CONSTRAINT "PK_AV" PRIMARY KEY ("NUAVION") ENABLE
   )
/
CREATE TABLE  "PILOTE" 
   (	"NOPILOTE" CHAR(4), 
	"NOM" VARCHAR2(35), 
	"ADRESSE" VARCHAR2(30), 
	"SAL" NUMBER(8,2), 
	"COMM" NUMBER(8,2) DEFAULT '', 
	"EMBAUCHE" DATE, 
	 PRIMARY KEY ("NOPILOTE") ENABLE
   )
/
CREATE TABLE  "VOL" 
   (	"NOVOL" CHAR(6), 
	"VILDEP" VARCHAR2(30), 
	"VILAR" VARCHAR2(30), 
	"DEPH" NUMBER(2,0), 
	"DEPMN" NUMBER(2,0), 
	"ARH" NUMBER(2,0), 
	"ARMN" NUMBER(2,0), 
	"CHJOUR" NUMBER(1,0), 
	 PRIMARY KEY ("NOVOL") ENABLE
   )
/

CREATE TABLE  "AFFECTATION" 
   (	"VOL" CHAR(6), 
	"DATEVOL" DATE, 
	"PILOTE" CHAR(4), 
	"AVION" CHAR(4), 
	"NBPASS" NUMBER(3,0), 
	 CONSTRAINT "fk1_AFF" FOREIGN KEY("VOL") REFERENCES VOL("NOVOL") ENABLE,
       CONSTRAINT "fk2_AFF" FOREIGN KEY("PILOTE") REFERENCES PILOTE("NOPILOTE") ENABLE,
       CONSTRAINT "PK_AFF" PRIMARY KEY ("VOL", "DATEVOL") ENABLE
   )
/
